### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by shengquan-ni**

### CODE REVIEW

**Comment by chenlica** [comment]
High-level comments:

- Rename "OrleansExp" to something different, such as "AmberOnOrleans".
- Write a paragraph to give an overview of this project.  Mention the main motivation, features, and the Amber paper.

**Comment by chenlica** [comment]
I got some errors when running "npm install".  Here are some of them.  I tried to run "npm audit fix" but those error remained.

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)

updated 3 packages and audited 2128 packages in 30.359s

44 packages are looking for funding
  run `npm fund` for details

found 413 vulnerabilities (345 low, 44 moderate, 24 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by chenlica** [comment]
"npm run build" failed for me.

**Comment by shengquan-ni** [comment]
1. "OrleansExp" is renamed to "AmberOnOrleans"
2. Introduction section added.
3. The folder structure has changed.
4. The silo concept is explained and other steps are polished.

**Comment by shengquan-ni** [comment]
already merged

**Pull request closed without merging**
